---

name: Deploy branch to staging environment

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'


jobs:
  create_deployment:
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: 'https://cg-vm1-deployments.scilifelab.se/docs'
      description: "cg_deployment"
    steps:
      - run: echo Deplyment to stage submitted
