name: Deploy Staging
on:
  issue_comment:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Check for trigger word
      uses: khan/pull-request-comment-trigger@master
      id: check
      with:
        trigger: '/deploy'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

    - name: start deployment
      if: steps.check.outputs.triggered == 'true'
      uses: bobheadxi/deployments@v0.6.0
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: stage
        ref: ${{ github.head_ref }}