on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'

jobs:
  print_tags:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Tags: ${{ github.event.inputs.tags }}"